-- Placeholder migration file
-- Actual migrations will be created in Phase 4 (Authentication & Database Layer)
-- This file ensures the migrations directory structure is in place

-- Example structure for future api_keys table:
-- CREATE TABLE IF NOT EXISTS api_keys (
--   id SERIAL PRIMARY KEY,
--   key_hash VARCHAR(255) NOT NULL UNIQUE,
--   name VARCHAR(100) NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   active BOOLEAN DEFAULT true
-- );
